# Generated by Django 3.2.2 on 2021-05-23 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20210520_1343'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=40)),
                ('addrerss', models.CharField(max_length=50)),
                ('addrerss_line_2', models.CharField(max_length=500)),
                ('state', models.CharField(max_length=500)),
                ('city', models.CharField(max_length=500)),
                ('zip_ord', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=10)),
            ],
        ),
    ]
