# Generated by Django 3.2.2 on 2021-05-23 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_rename_zip_ord_orders_zip_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='addrerss',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='addrerss_line_2',
            new_name='address_line_2',
        ),
    ]
