# Generated by Django 3.2.2 on 2021-05-23 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20210523_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
