# Generated by Django 3.2.2 on 2021-05-23 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_orders_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='item_json',
            new_name='ItemJson',
        ),
    ]
